# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 10
  identifier = "homepage"

[[main]]
  name = "About"
  url = "#about"
  weight = 20
  parent = "homepage"

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30
  parent = "homepage"

[[main]]
  name = "Research"
  url = "#publications"
  weight = 40
  parent = "homepage"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
  parent = "homepage"

[[main]]
  name = "Blog"  # Title of the link.
  url = "blog/"  # Widget Page folder name.
  weight = 100  # Position of the link in the navigation bar.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 70
